// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdqsgswrkrxjeesahshc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkcXNnc3dya3J4amVlc2Foc2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODUzNTcsImV4cCI6MjA2Mzk2MTM1N30.1zcvmxi8ldSRWPoNmYO8yNTYmCYUKDBF6T3I_e-xVOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});